# Apa itu SVD

Singular Value Decomposition (SVD) adalah salah satu teknik penting dalam aljabar linear yang digunakan untuk memecah (dekomposisi) sebuah matriks menjadi tiga matriks lain yang lebih sederhana. SVD banyak digunakan dalam berbagai bidang seperti kompresi gambar, rekomendasi sistem (seperti Netflix atau YouTube), pengolahan sinyal, dan machine learning.

## Kegunaan SVD

1. Reduksi Dimensi:
SVD membantu mengurangi jumlah variabel dalam dataset, yang dikenal sebagai reduksi dimensi.
Dengan mempertahankan hanya sebagian nilai singular dan vektor singular yang paling penting, SVD dapat menghasilkan representasi data yang lebih ringkas tanpa kehilangan informasi yang signifikan.
Contoh umum adalah penggunaan SVD dalam Principal Component Analysis (PCA).
2. Kompresi Data:
SVD dapat digunakan untuk mengompresi data, seperti gambar dan audio, dengan membuang informasi yang kurang penting dan mempertahankan yang paling penting.
Dalam pemrosesan gambar, SVD membantu mengurangi ukuran file gambar sambil mempertahankan kualitas visual yang memadai.
3. Pemrosesan Sinyal:
SVD dapat digunakan untuk menyaring sinyal dan menghilangkan gangguan dalam pemrosesan sinyal.
Ini membantu dalam mengidentifikasi pola penting dalam data dan menghilangkan kebisingan.
4. Analisis Citra:
SVD dapat digunakan untuk mengekstraksi fitur penting dari citra, yang berguna dalam pengenalan pola atau pengenalan wajah.
SVD juga membantu dalam pemulihan citra yang rusak atau terdegradasi.
5. Rekomendasi Sistem:
SVD digunakan dalam sistem rekomendasi untuk memprediksi peringkat pengguna pada item berdasarkan matriks pengguna-item.
Dengan memfaktorkan matriks peringkat, SVD dapat membantu mengidentifikasi pola dan rekomendasi yang relevan.
6. Pencocokan Data Kuadrat Terkecil:
SVD dapat digunakan untuk menyelesaikan masalah kuadrat terkecil dalam analisis regresi dan masalah pencocokan data lainnya.
Secara umum, SVD adalah alat yang kuat untuk memahami struktur data dan mengekstrak informasi yang paling penting, membuatnya berguna dalam berbagai bidang ilmu, teknik, dan statistik.

## Bagaimana formula SVD

Untuk sebuah matriks A berukuran $m \times n$, SVD menyatakan bahwa:

$$
A = U \Sigma V^T
$$

di mana:

* $A$: matriks asli berukuran $m \times n$
* $U$: matriks ortogonal berukuran $m \times m$
* $\Sigma$: matriks diagonal berukuran $m \times n$, berisi nilai singular (singular values)
* $V^T$: transpose dari matriks ortogonal $V$ berukuran $n \times n$

Penjelasan Komponen

* Singular values (nilai singular) adalah akar dari eigenvalue matriks $A^TA$ atau $AA^T$.
* Kolom-kolom U adalah eigenvektor dari $AA^T$.
* Kolom-kolom V adalah eigenvektor dari $A^TA$.
* Matriks $\Sigma$ hanya memiliki nilai non-nol di diagonal utama dan sisanya nol.

Contoh Sederhana

Misalkan matriks:

$$
A = \begin{bmatrix}
3 & 1 \\
1 & 3 \\
\end{bmatrix}
$$

Kita bisa melakukan dekomposisi $A = U \Sigma V^T$, dengan hasil akhir (dibantu komputer):

$$
U = \begin{bmatrix}
-0.707 & -0.707 \\
-0.707 &  0.707 \\
\end{bmatrix}, \quad
\Sigma = \begin{bmatrix}
4 & 0 \\
0 & 2 \\
\end{bmatrix}, \quad
V^T = \begin{bmatrix}
-0.707 & -0.707 \\
-0.707 &  0.707 \\
\end{bmatrix}
$$



In [ ]:
import numpy as np

# Matriks asli
A = np.array([
    [3, 1],
    [1, 3]
])

# SVD dengan NumPy
U, S, VT = np.linalg.svd(A)

print("Matrix A:")
print(A)
print("\nU:")
print(U)
print("\nSingular values (S):")
print(S)
print("\nV^T:")
print(VT)

# Bentuk S ke dalam bentuk matriks diagonal (Sigma)
Sigma = np.zeros_like(A, dtype=float)
np.fill_diagonal(Sigma, S)

print("\nSigma:")
print(Sigma)

# Perkalian kembali: U @ Sigma @ V^T
A_reconstructed = U @ Sigma @ VT

print("\nRekonstruksi A dari UΣV^T:")
print(A_reconstructed)

# Cek apakah hasilnya sama
print("\nApakah A sama dengan rekonstruksi? ", np.allclose(A, A_reconstructed))


Matrix A:
[[3 1]
 [1 3]]

U:
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

Singular values (S):
[4. 2.]

V^T:
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

Sigma:
[[4. 0.]
 [0. 2.]]

Rekonstruksi A dari UΣV^T:
[[3. 1.]
 [1. 3.]]

Apakah A sama dengan rekonstruksi?  True


### Perhitungan Manual Matriks 4x2
Diketahui:
$$
A =
\begin{bmatrix}
3 & 7 \\
2 & 5 \\
4 & 3 \\
1 & 1 \\
\end{bmatrix}
\quad \text{(ukuran 4 × 2)}
$$

Kita akan melakukan **Singular Value Decomposition (SVD)** terhadap matriks ini, yaitu:

$$
A = U \cdot \Sigma \cdot V^T
$$


Langkah-Langkah Singkat (Manual Konsep)

1. Hitung $A^T A$

Karena A adalah 4×2, maka $A^T$ adalah 2×4, sehingga:

$$
A^T A =
\begin{bmatrix}
3 & 2 & 4 & 1 \\
7 & 5 & 3 & 1 \\
\end{bmatrix}
\cdot
\begin{bmatrix}
3 & 7 \\
2 & 5 \\
4 & 3 \\
1 & 1 \\
\end{bmatrix}
$$

Kalikan baris × kolom:

$$
A^T A =
\begin{bmatrix}
3^2 + 2^2 + 4^2 + 1^2 & 3×7 + 2×5 + 4×3 + 1×1 \\
3×7 + 2×5 + 4×3 + 1×1 & 7^2 + 5^2 + 3^2 + 1^2 \\
\end{bmatrix}
$$

Hitung elemen-elemennya:

* $3^2 + 2^2 + 4^2 + 1^2 = 9 + 4 + 16 + 1 = 30$
* $3×7 + 2×5 + 4×3 + 1×1 = 21 + 10 + 12 + 1 = 44$
* $7^2 + 5^2 + 3^2 + 1^2 = 49 + 25 + 9 + 1 = 84$

Jadi:

$$
A^T A =
\begin{bmatrix}
30 & 44 \\
44 & 84 \\
\end{bmatrix}
$$


2. Hitung **eigenvalue** dari $A^T A$

Cari $\lambda$ dari:

$$
\left|
\begin{matrix}
30 - \lambda & 44 \\
44 & 84 - \lambda \\
\end{matrix}
\right| = 0
$$

$$
(30 - \lambda)(84 - \lambda) - 44^2 = 0
\Rightarrow
\lambda^2 - 114\lambda + (2520 - 1936) = 0
\Rightarrow
\lambda^2 - 114\lambda + 584 = 0
$$

Gunakan rumus kuadrat:

$$
\lambda = \frac{114 \pm \sqrt{114^2 - 4 \cdot 584}}{2}
= \frac{114 \pm \sqrt{12996 - 2336}}{2}
= \frac{114 \pm \sqrt{10660}}{2}
$$

$$
\sqrt{10660} \approx 103.25
$$

$$
\lambda_1 \approx \frac{114 + 103.25}{2} = 108.625, \quad
\lambda_2 \approx \frac{114 - 103.25}{2} = 5.375
$$


3. Cari **singular values** = akar dari eigenvalue:

$$
\sigma_1 = \sqrt{108.625} \approx 10.42, \quad
\sigma_2 = \sqrt{5.375} \approx 2.32
$$


4. Bangun matriks $\Sigma$

Karena A adalah 4×2, maka $\Sigma$ adalah 4×2:

$$
\Sigma =
\begin{bmatrix}
10.42 & 0 \\
0 & 2.32 \\
0 & 0 \\
0 & 0 \\
\end{bmatrix}
$$


5. Matriks $V$ dan $U$

* $V$ berasal dari eigenvector $A^T A$
* $U = \frac{1}{\sigma_i} A v_i$


Kesimpulan SVD:

$$
A_{4×2} = U_{4×4} \cdot \Sigma_{4×2} \cdot V^T_{2×2}
$$

Dengan:

* $\Sigma = \begin{bmatrix} 10.42 & 0 \\ 0 & 2.32 \\ 0 & 0 \\ 0 & 0 \end{bmatrix}$
* $V$: eigenvector dari $A^T A$
$$
V^T =
\begin{bmatrix}
-0.488 & -0.873 \\
-0.873 &  0.488 \\
\end{bmatrix}
$$

> Baris-barisnya adalah vektor eigen dari $A^T A$

* $U$: dihitung dari $Av_i / \sigma_i$

$$
U =
\begin{bmatrix}
-0.727 & -0.345 & -0.574 & -0.153 \\
-0.512 & -0.300 &  0.792 &  0.139 \\
-0.439 &  0.874 &  0.082 & -0.195 \\
-0.131 &  0.166 & -0.190 &  0.959 \\
\end{bmatrix}
$$

> Kolom-kolom $U$ adalah vektor ortonormal yang membentang ruang kolom dari $A$.

In [ ]:
import numpy as np

# Matriks asli
A = np.array([
    [3, 7],
    [2, 5],
    [4, 3],
    [1, 1]
])

# SVD dengan NumPy
U, S, VT = np.linalg.svd(A)

print("Matrix A:")
print(A)
print("\nU:")
print(U)
print("\nSingular values (S):")
print(S)
print("\nV^T:")
print(VT)

# Bentuk S ke dalam bentuk matriks diagonal (Sigma)
Sigma = np.zeros_like(A, dtype=float)
np.fill_diagonal(Sigma, S)

print("\nSigma:")
print(Sigma)

# Perkalian kembali: U @ Sigma @ V^T
A_reconstructed = U @ Sigma @ VT

print("\nRekonstruksi A dari UΣV^T:")
print(A_reconstructed)

# Cek apakah hasilnya sama
print("\nApakah A sama dengan rekonstruksi? ", np.allclose(A, A_reconstructed))


Matrix A:
[[3 7]
 [2 5]
 [4 3]
 [1 1]]

U:
[[-0.72667296 -0.34526321 -0.57386797 -0.15302052]
 [-0.51235825 -0.300381    0.79239419  0.13918232]
 [-0.4386146   0.87355405  0.0817107  -0.19453511]
 [-0.13058586  0.16573437 -0.19002726  0.95883737]]

Singular values (S):
[10.42226645  2.31869834]

V^T:
[[-0.48835631 -0.87264432]
 [ 0.87264432 -0.48835631]]

Sigma:
[[10.42226645  0.        ]
 [ 0.          2.31869834]
 [ 0.          0.        ]
 [ 0.          0.        ]]

Rekonstruksi A dari UΣV^T:
[[3. 7.]
 [2. 5.]
 [4. 3.]
 [1. 1.]]

Apakah A sama dengan rekonstruksi?  True
