## Matrik
### Definisi Matrik
Matrik adalah susunan bilangan real atau bilangan kompleks (atau elemen-elemen) yang disusun dalam baris dan kolom sehingga membentuk jajaran persegi panjang. Matrik disusun berdasarkan baris dan kolom, serta ditempatkan di dalam tanda kurung. Ukuran matrik ditentukan oleh jumlah baris dan kolom yang dikandungnya.

Matrik diberi nama dengan huruf kapital dan anggotannya dinyatakan dengan huruf kecil. Banyaknya baris dan kolom suatu matriks disebut ordo. Berikut adalah beberapa contoh matrik.

1. Matrik 4 x4

$$
\begin{split}
A = \left[ \begin{array}{rrrr}
1 & 8 & 9 & 4 \\
2 & 7 & -1 & -3 \\
2 & 6 & 2 & 5 \\
4 & 5 & 3 & -2  \\
\end{array}\right]
\end{split}
$$

2. Matrik 3 x 2

$$
\begin{split}
B = \left[ \begin{array}{rrrr}
3 & 9 \\
5 & 3 \\
7 & 1 \\
\end{array}\right]
\end{split}
$$

3. Matrik 2 x 2

$$
\begin{split}
C = \left[ \begin{array}{rrrr}
-1 & 9 \\
3 & 5 \\
\end{array}\right]
\end{split}
$$

4. Matrik 2 x 3

$$
\begin{split}
D = \left[ \begin{array}{rrrr}
-2 & 8 & 3 \\
-3 & 9 & 7 \\
\end{array}\right]
\end{split}
$$

### Operasi Artimatika Matrik
Operasi aritmatika matrik adalah serangkaian operasi matematika yang dilakukan pada matrik meliputi penjumlahan, pengurangan, perkalian, perkalian dengan skalar.

### Penjumlahan
Penjumlahan matrik adalah operasi antara dua matrik yang memiliki dimensi yang sama yaitu jumlah baris dan kolomnya harus sama. Operasi penjumlahan dilakukan dengan menjumlahkan elemen-elemen yang sesuai dari kedua matrik.

### Konsep Penjumlahan Matrik
Berikut contoh penjumlahan matrik.


In [ ]:
import numpy as np
a = np.array(([2,3],[9,1]))
b = np.array(([5,7],[8,2]))

c = np.add (a,b)
print(a)
print()
print(b)
print()
print("hasil : ")
print(c)

[[2 3]
 [9 1]]

[[5 7]
 [8 2]]

hasil : 
[[ 7 10]
 [17  3]]


### Perkalian Matrik
Perkalian matrik adalah nilai pada matrik yang bisa dihasilkan dengan cara dikalikan-nya tiap baris degan kolom yang memiliki jumlah baris yang sama. Operasi ini melibatkan perkalian elemen-elemen matrik. Untuk melakukan perkalian matrik A dan B, jumlah kolom dalam matrik A harus sama dengan jumlah baris dalam matrik B.

### Konsep Perkalian Matrik
Berikut contoh perkalian matrik.

In [ ]:
import numpy as np
a = np.array(([1,2,3],[4,5,6],[7,8,9]))
b = np.array(([9,8,7],[6,5,4],[3,2,1]))

c = np.matmul(a,b)
print(a)
print()
print(b)
print()
print("hasil : ")
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[9 8 7]
 [6 5 4]
 [3 2 1]]

hasil : 
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


## Penyelesaian persamaan menggunakan invers matrik

Kita diberikan sistem persamaan linear:

$
\begin{aligned}
    -7x_1 - 6x_2 - 12x_3 &= -33 \\
    5x_1 + 5x_2 + 7x_3 &= 24 \\
    x_1 + 4x_3 &= 5
\end{aligned}
$

#### **1. Bentuk Matriks**
Sistem persamaan di atas dapat dituliskan dalam bentuk matriks:

$
A \mathbf{x} = \mathbf{b}
$

dengan:

$
A =
\begin{bmatrix}
-7 & -6 & -12 \\
5 & 5 & 7 \\
1 & 0 & 4
\end{bmatrix},
\quad
\mathbf{x} =
\begin{bmatrix}
x_1 \\ x_2 \\ x_3
\end{bmatrix},
\quad
\mathbf{b} =
\begin{bmatrix}
-33 \\ 24 \\ 5
\end{bmatrix}
$

Penyelesaian sistem menggunakan invers matriks diberikan oleh:

$
\mathbf{x} = A^{-1} \mathbf{b}
$

Kita akan mencari $ A^{-1} $ menggunakan operasi baris elementer.

---

#### **2. Menentukan $ A^{-1} $ Menggunakan Operasi Baris Elementer**
Kita mulai dengan matriks augmented:

$
\left[ A \,|\, I \right] =
\left[
\begin{array}{ccc|ccc}
-7 & -6 & -12 & 1 & 0 & 0 \\
5 & 5 & 7 & 0 & 1 & 0 \\
1 & 0 & 4 & 0 & 0 & 1
\end{array}
\right]
$

**Langkah 1: Ubah elemen (1,1) menjadi 1**
Kita bagi baris pertama dengan $ -7 $:

$
\left[
\begin{array}{ccc|ccc}
1 & \frac{6}{7} & \frac{12}{7} & -\frac{1}{7} & 0 & 0 \\
5 & 5 & 7 & 0 & 1 & 0 \\
1 & 0 & 4 & 0 & 0 & 1
\end{array}
\right]
$

**Langkah 2: Nulifikasi elemen (2,1) dan (3,1)**  
Baris kedua: $ R_2 \leftarrow R_2 - 5R_1 $  
Baris ketiga: $ R_3 \leftarrow R_3 - R_1 $

$
\left[
\begin{array}{ccc|ccc}
1 & \frac{6}{7} & \frac{12}{7} & -\frac{1}{7} & 0 & 0 \\
0 & \frac{5}{7} & \frac{1}{7} & \frac{5}{7} & 1 & 0 \\
0 & -\frac{6}{7} & \frac{16}{7} & \frac{1}{7} & 0 & 1
\end{array}
\right]
$

**Langkah 3: Ubah elemen (2,2) menjadi 1**  
Kita kalikan baris kedua dengan $ \frac{7}{5} $:

$
\left[
\begin{array}{ccc|ccc}
1 & \frac{6}{7} & \frac{12}{7} & -\frac{1}{7} & 0 & 0 \\
0 & 1 & \frac{1}{5} & \frac{1}{5} & \frac{7}{5} & 0 \\
0 & -\frac{6}{7} & \frac{16}{7} & \frac{1}{7} & 0 & 1
\end{array}
\right]
$

**Langkah 4: Nulifikasi elemen (1,2) dan (3,2)**  
Baris pertama: $ R_1 \leftarrow R_1 - \frac{6}{7} R_2 $  
Baris ketiga: $ R_3 \leftarrow R_3 + \frac{6}{7} R_2 $

$
\left[
\begin{array}{ccc|ccc}
1 & 0 & \frac{10}{7} & -\frac{5}{21} & -\frac{6}{5} & 0 \\
0 & 1 & \frac{1}{5} & \frac{1}{5} & \frac{7}{5} & 0 \\
0 & 0 & \frac{22}{7} & \frac{11}{35} & \frac{42}{35} & 1
\end{array}
\right]
$

**Langkah 5: Ubah elemen (3,3) menjadi 1**  
Kita kalikan baris ketiga dengan $ \frac{7}{22} $:

$
\left[
\begin{array}{ccc|ccc}
1 & 0 & \frac{10}{7} & -\frac{5}{21} & -\frac{6}{5} & 0 \\
0 & 1 & \frac{1}{5} & \frac{1}{5} & \frac{7}{5} & 0 \\
0 & 0 & 1 & \frac{1}{10} & \frac{21}{22} & \frac{7}{22}
\end{array}
\right]
$

**Langkah 6: Nulifikasi elemen (1,3) dan (2,3)**  
Baris pertama: $ R_1 \leftarrow R_1 - \frac{10}{7} R_3 $  
Baris kedua: $ R_2 \leftarrow R_2 - \frac{1}{5} R_3 $

$
\left[
\begin{array}{ccc|ccc}
1 & 0 & 0 & -\frac{8}{21} & -\frac{9}{5} & -\frac{10}{22} \\
0 & 1 & 0 & \frac{1}{5} - \frac{1}{50} & \frac{7}{5} - \frac{21}{110} & -\frac{7}{110} \\
0 & 0 & 1 & \frac{1}{10} & \frac{21}{22} & \frac{7}{22}
\end{array}
\right]
$

Setelah disederhanakan, kita dapatkan invers matriks $ A^{-1} $:

$
A^{-1} =
\begin{bmatrix}
-\frac{8}{21} & -\frac{9}{5} & -\frac{5}{11} \\
\frac{2}{7} & \frac{37}{35} & -\frac{7}{55} \\
\frac{1}{10} & \frac{21}{22} & \frac{7}{22}
\end{bmatrix}
$

---

#### **3. Menghitung $ \mathbf{x} = A^{-1} \mathbf{b} $**

$
\mathbf{x} =
\begin{bmatrix}
-\frac{8}{21} & -\frac{9}{5} & -\frac{5}{11} \\
\frac{2}{7} & \frac{37}{35} & -\frac{7}{55} \\
\frac{1}{10} & \frac{21}{22} & \frac{7}{22}
\end{bmatrix}
\begin{bmatrix}
-33 \\ 24 \\ 5
\end{bmatrix}
$

Setelah dihitung, diperoleh:

$
\mathbf{x} =
\begin{bmatrix}
1 \\ 2 \\ 1
\end{bmatrix}
$

Jadi, solusi dari sistem persamaan adalah:

$
x_1 = 1, \quad x_2 = 2, \quad x_3 = 1
$

## Determinan Matrik
Determinan matrik adalah suatu nilai skalar yang dihitung dari elemen-elemen dalam matrik persegi. Determinan matrik hanya dapat dicari dengan matrik persegi. Determinan dari matrik A dapat ditulis det(A) atau |A|.

### Minor Matrik
Minor matrik adalah determinan dari submatrik yang diperoleh dengan menghapus baris dan kolom tertentu dari matrik aslinya. Minor digunakan dalam perhitungan cofactor dan determinan matrik berukuran lebih besar.

### Cofactor Matrik
Cofactor matrik adalah matrik baru yang elemen-elemennya dalah cofactor dari matrik asalnya, yang diperoleh dengan mengalikan minor elemen matrik dengan
$(-1)^{i+j}$ . Cofactor digunakan dalam menghitung determinan dan invers matrik.

### Mencari determinan dengan konsep minor dan cofactor matrik. Berikan contoh matrik $3 \times 3$, $4 \times 4$, dan $5 \times 5$ <br><br>

### 1. Determinan Matrik $3 \times 3$

$
A = \begin{bmatrix}
2 & 3 & 1 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}
$

**Menentukan determinan menggunakan ekspansi baris pertama :**

$
\det(A) = 2C_{11} - 3C_{12} + 1C_{13}
$

- **Minor dan Kofaktor:**

Minor $M_{11}$ adalah determinan dari submatriks yang diperoleh dengan menghapus baris 1 dan kolom 1:

$\begin{aligned}
   M_{11} &= \begin{vmatrix} 5 & 6 \\ 8 & 9 \end{vmatrix} \\
          &= (5 \times 9) - (6 \times 8) \\
          &= 45 - 48 \\
          &= -3
\end{aligned}$

Cofactor :

$\begin{aligned}
    C_{11} &= (-1)^{1+1} M_{11} \\
           &= (-1)^2 (-3) \\
           &= -3
\end{aligned}$

Minor $M_{12}$ adalah determinan dari submatriks yang diperoleh dengan menghapus baris 1 dan kolom 2:

$\begin{aligned}
   M_{12} &= \begin{vmatrix} 4 & 6 \\ 7 & 9  \end{vmatrix} \\
          &= (4 \times 9) - (6 \times 7) \\
          &= 36 - 42 \\
          &= -6
\end{aligned}$

Cofaktor:

$\begin{aligned}
    C_{12} &= (-1)^{1+2} M_{12} \\
           &= (-1)^3 (-6) \\
           &= 6
\end{aligned}$

Minor $M_{13}$ adalah determinan dari submatriks yang diperoleh dengan menghapus baris 1 dan kolom 3:

$\begin{aligned}
   M_{13} &= \begin{vmatrix} 4 & 5 \\ 7 & 8  \end{vmatrix} \\
          &= (4 \times 8) - (5 \times 7) \\
          &= 32 - 35 \\
          &= -3
\end{aligned}$

Kofaktor:

$\begin{aligned}
    C_{13} &= (-1)^{1+3} M_{13} \\
           &= (-1)^4 (-3) \\
           &= -3
\end{aligned}$

- **Determinan**

$
\det(A) = a_{11}C_{11} - a_{12}C_{12} + a_{13}C_{13}
$

$\begin{aligned}
    \det(A) &= (2 \times -3) - (3 \times 6) + (1 \times -3) \\
            &= -6 - 18 - 3 \\
            &= -27
\end{aligned}$

### 2. Determinan Matrik $4 \times 4$

$
B = \begin{bmatrix}
1 & 2 & 3 & 4 \\
2 & 3 & 4 & 3 \\
3 & 4 & 1 & 2 \\
4 & 3 & 2 & 1
\end{bmatrix}
$

**Menentukan determinan menggunakan ekspansi baris pertama :**

$
\det(B) = 1C_{11} - 2C_{12} + 3C_{13} - 4C_{14}
$

- **Minor dan Kofaktor:**

Minor $M_{11}$ :

$\begin{aligned}
   M_{11} &= \begin{vmatrix} 1 & 4 & 3 \\ 4 & 1 & 2 \\ 3 & 2 & 1 \\  \end{vmatrix} \\
          &= 1 (1 \times 1 - 2 \times 2) - 4 (4 \times 1 - 2 \times 3) + 3 (4 \times 2 - 1 \times 3) \\
          &= 1 (1 - 4) - 4 (4 - 6) + 3 (8 - 3) \\
          &= 1 (-3) - 4 (-2) + 3 (5)\\
          &= -3 + 8 + 15\\
          &= 20
\end{aligned}$

Cofactor :

$\begin{aligned}
    C_{11} &= (-1)^{1+1} M_{20} \\
           &= (-1)^2 (20) \\
           &= 20
\end{aligned}$

Minor $M_{12}$ :

$\begin{aligned}
   M_{12} &= \begin{vmatrix} 2 & 4 & 3 \\ 3 & 1 & 2 \\ 2 & 2 & 1 \\  \end{vmatrix} \\
          &= 2 (1 \times 1 - 2 \times 2) - 4 (3 \times 1 - 2 \times 4) + 3 (3 \times 2 - 1 \times 4) \\
          &= 2 (1 - 4) - 4 (3 - 8) + 3 (6 - 4) \\
          &= 2 (-3) - 4 (-5) + 3 (2)\\
          &= -6 + 20 + 6\\
          &= -20
\end{aligned}$

Cofactor :

$\begin{aligned}
    C_{12} &= (-1)^{1+2} M_{20} \\
           &= (-1)^3 (20) \\
           &= -20
\end{aligned}$

Minor $M_{13}$ :

$\begin{aligned}
   M_{13} &= \begin{vmatrix}  2 & 1 & 3 \\ 3 & 4 & 2 \\ 4 & 3 & 1 \\ \end{vmatrix} \\
          &= 2 (4 \times 1 - 2 \times 3) - 1 (3 \times 1 - 2 \times 4) + 3 (3 \times 3 - 3 \times 4 - 4) \\
          &= 2 (4 - 6) - 1 (3 - 8) + 3 (9 - 16) \\
          &= 2 (-2) - 1 (-5) + 3 (-7)\\
          &= -4 + 5 - 21\\
          &= -20
\end{aligned}$

Cofactor :

$\begin{aligned}
    C_{13} &= (-1)^{1+3} M_{-20} \\
           &= (-1)^4 (-20) \\
           &= -20
\end{aligned}$

Minor $M_{14}$ :

$\begin{aligned}
   M_{14} &= \begin{vmatrix}  2 & 1 & 4 \\ 3 & 4 & 1 \\ 4 & 3 & 2 \\ \end{vmatrix} \\
          &= 2 (4 \times 2 - 1 \times 3) - 1 (3 \times 2 - 1 \times 4) + 4 (3 \times 3 - 4 \times 4 ) \\
          &= 2 (8 - 3) - 1 (6 - 4) + 4 (9 - 16) \\
          &= 2 (5) - 1 (2) + 4 (-7)\\
          &= 10 - 2 - 28\\
          &= -20
\end{aligned}$

Cofactor :

$\begin{aligned}
    C_{14} &= (-1)^{1+4} M_{-20} \\
           &= (-1)^5 (-20) \\
           &= 20
\end{aligned}$

- **Determinan**

$
\det(B) = 1C_{11} - 2C_{12} + 3C_{13} - 4C_{14}
$

$\begin{aligned}
    \det(B) &= (1 \times 20) - (2 \times -20) + (3 \times -20) - (4 \times 20)\\
            &= 20 + 40 - 60 - 80 \\
            &= -80
\end{aligned}$

### 3. Determinan Matrik $5 \times 5$

$
C = \begin{bmatrix}
1 & 2 & 3 & 4 & 5 \\
6 & 7 & 8 & 9 & 10 \\
11 & 12 & 13 & 14 & 15 \\
16 & 17 & 18 & 19 & 20 \\
21 & 22 & 23 & 24 & 25
\end{bmatrix}
$

**Menentukan determinan menggunakan ekspansi baris pertama :**

$
\det(C) = 1C_{11} - 2C_{12} + 3C_{13} - 4C_{14} - 5C_{15}
$

- **Minor dan Kofaktor:**

Minor $M_{11}$ :

$M_{11} = \begin{vmatrix} 7 & 8 & 9 & 10 \\ 12 & 13 & 14 & 15 \\ 17 & 18 & 19 & 20 \\ 22 & 23 & 24 & 25 \end{vmatrix}$

Kita hitung minor $3 \times 3$

$\begin{aligned}
   M_{11} &= \begin{vmatrix}  13 & 14 & 15 \\ 18 & 19 & 20 \\ 23 & 24 & 25 \end{vmatrix} \\
          &= 13 (19 \times 25 - 20 \times 24) - 14 (18 \times 25 - 20 \times 23) + 15 (18 \times 24 - 19 \times 23) \\
          &= 13 (475 - 480) - 14 (450 - 460) + 15 (432 - 437) \\
          &= 13 (-5) - 14 (-10) + 15 (-5)\\
          &= -65 + 140 -75\\
          &= 0
\end{aligned}$

Cofactor :

$\begin{aligned}
    C_{11} &= (-1)^{1+1} M_{20} \\
           &= (-1)^2 (0) \\
           &= 0
\end{aligned}$

- **Determinan**

$
\det(C) = 1C_{11} - 2C_{12} + 3C_{13} - 4C_{14} + 5C_{15}
$

Karena setiap minor dari baris pertama menghasilkan determinan 0, maka :

$\begin{aligned}
    \det(C) &= 1 (0) - 2 (0) + 3 (0) - 4 (0) + 5 (0)\\
            &= 0
\end{aligned}$